### PR TITLE
General SWIG improvements

### PR DESCRIPTION
**Pull request by earlchew**
Signed-off-by: Earl Chew <earl@cohodata.com>

### CODE REVIEW

**Comment by earlchew** [comment]
https://github.com/sahlberg/libnfs-python/issues/18

**Comment by earlchew** [comment]
https://github.com/sahlberg/libnfs-python/issues/20

**Comment by earlchew** [comment]
https://github.com/sahlberg/libnfs-python/issues/21

**Comment by earlchew** [comment]
https://github.com/sahlberg/libnfs-python/issues/22

**Comment by earlchew** [comment]
https://github.com/sahlberg/libnfs-python/issues/23

**Comment by earlchew** [comment]
https://github.com/sahlberg/libnfs-python/issues/24

**Comment by sahlberg** [comment]
Merged, thanks!

I think python nfs bindings should be very important and useful for a bunch of projects and usecases.
I think the current python bindings are functional and useful   but they could, and should, be maintained
better and expanded upon so they become fully python-ish, and fully packaged and made available in the
different python module repos.

This require a proper maintainer for libnfs-python. Do you wish to take over maintenance of this project ?
I have so many other projects I prioritize higher that I am making libnfs-python a disservice.

**Pull request merged**
